services:
  - type: web
    name: student-performance-analyzer
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /
    domains:
      - app.csbblr.online
    envVars:
      - key: APP_DATA_DIR
        value: ""
      - key: TZ
        value: Asia/Kolkata
